//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagerSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class createPatientInvoice
    {
        public int id { get; set; }
        public string incoiceName { get; set; }
        public string invoiceNumber { get; set; }
        public string diagnosis { get; set; }
        public string diagnosisNotes { get; set; }
        public string prescription { get; set; }
        public string prescribingDoctorName { get; set; }
        public string referenceDoctorName { get; set; }
        public string amount { get; set; }
        public string paymentMode { get; set; }
        public string balance { get; set; }
        public string itemPrice { get; set; }
    }
}
