//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagerSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class logBankDetail
    {
        public int id { get; set; }
        public string chequeNr { get; set; }
        public System.DateTime bankingDate { get; set; }
        public string amount { get; set; }
        public string personelIncharge { get; set; }
    }
}
