//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagerSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public int id { get; set; }
        public string supplierID { get; set; }
        public string supplierName { get; set; }
    }
}
